[server]
# Performance optimizations
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

# Logging configuration - reduce noise
level = "WARNING"
enableStaticServing = true

[browser]
# UI optimizations
gatherUsageStats = false
showErrorDetails = true

[theme]
# Clean, professional theme
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[logger]
# Reduce logging noise
level = "WARNING"
enableStaticServing = true

[client]
# Performance settings
showErrorDetails = true
toolbarMode = "minimal"